### ISSUE TITLE
Latest commits broke my PDAL interface

### ISSUE THREAD

**Issue by oscarkramer** [PDAL/pdal.github.io#5]
I see there are some class name changes and associated header file name changes. These broke my build (OSSIM PDAL plugin). I see PointBuffer became PointView, but I have other unresolved classes:

PointContextRef
PointBufferSet
PointBufferPtr

Is there a summary of the changes somewhere so I can know what to change on my side?

-Oscar Kramer

**Comment by connormanning** [comment]
An overview is [here](https://github.com/PDAL/PDAL/pull/819).  It is likely that the changes have no functional effect on you, and that you just need to change some class names.  If you have implemented an `addDimensions` function, you will now be receiving a different parameter type than you previously did, but should be able to do the same things in that function.

In general, `PointContext[Ref] -> PointTable[Ref]`, `PointBuffer[Set/Ptr] -> PointView[Set/Ptr]`.  Hopefully that's helpful.

**Comment by oscarkramer** [comment]
It's building now with those replacements. Thanks.
